docs            
guest-agent     
guest-agent-msi 
pie             
modules         
debug-tcg       
debug-info      
sparse          
gnutls          
nettle          
gcrypt          
auth-pam   
sdl                                                                             
sdl-image       
gtk             
vte             
curses          
iconv           
vnc             
vnc-sasl        
vnc-jpeg        
vnc-png         
cocoa           
virtfs          
mpath 
xen   
xen-pci-passthrough
brlapi                                                        
curl            
membarrier     
fdt
bluez           
kvm                                                                          
hax                                                                          
hvf                    
whpx                     
rdma                                                 
pvrdma                                                                       
vde                                                                          
netmap                                               
linux-aio                                                                    
cap-ng                                                                       
attr                                                                         
vhost-net                                            
vhost-vsock            
